apiVersion: v1
kind: Service
metadata:
  name: clos-de-la-reine-back
  namespace: {{ include "clos.namespace" . }}
  labels:
    {{- include "clos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: clos-de-la-reine-back
  ports:
  - protocol: TCP
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
