# Default values for clos-de-la-reine (prod)
# Les images sont mises à jour par la CI (workflow build-and-push)

namespace: clos-de-la-reine
nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-secret

# Backend (Node)
backend:
  image: ghcr.io/emmguardia/clos-de-la-reine-back@sha256:365e54d64edf8e2415213456bc74a37ac9c88f75ddf9833d0aef5c6dc9dc8401
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  env:
    PORT: "3000"
    NODE_ENV: production
    JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private_key.pem
    EMAIL_SERVICE_URL: http://email-service.email-service.svc.cluster.local:8080
  secretName: clos-secrets
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 6
    cpuTarget: 70
    memoryTarget: 80

# Frontend (nginx)
frontend:
  image: ghcr.io/emmguardia/clos-de-la-reine-front@sha256:7e06e3783c74b66f666a5d451cef2119fa76a9504ff19015cccba6da172200f8
  replicas: 1
  serviceType: NodePort
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 6
    cpuTarget: 70
    memoryTarget: 80
