# Default values for clos-de-la-reine (prod)
# Les images sont mises à jour par la CI (workflow build-and-push)

namespace: clos-de-la-reine
nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-secret

# Backend (Node)
backend:
  image: ghcr.io/emmguardia/clos-de-la-reine-back@sha256:0a5ab047b453afcd922a51d3c0e12006c7d349f343017afd0f26454c79254276
  imagePullPolicy: IfNotPresent
  replicas: 2
  port: 3000
  env:
    PORT: "3000"
    NODE_ENV: production
    JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private_key.pem
    EMAIL_SERVICE_URL: http://email-service.email-service.svc.cluster.local:8080
  secretName: clos-secrets
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 2
    maxReplicas: 6
    cpuTarget: 70
    memoryTarget: 80

# Frontend (nginx)
frontend:
  image: ghcr.io/emmguardia/clos-de-la-reine-front@sha256:67d9448d7506ab75c427d7cd9c5f090af4be17b9ad4005511a82833d89585caa
  imagePullPolicy: Always
  replicas: 2
  serviceType: LoadBalancer
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  hpa:
    minReplicas: 2
    maxReplicas: 6
    cpuTarget: 70
    memoryTarget: 80
