# Default values for clos-de-la-reine (prod)
# Les images sont mises à jour par la CI (workflow build-and-push)

namespace: clos-de-la-reine
nameOverride: ""
fullnameOverride: ""

imagePullSecrets:
  - name: ghcr-secret

# Backend (Node)
backend:
  image: ghcr.io/emmguardia/clos-de-la-reine-back@sha256:f2a6d8358fb4c26f78951ad5180d566db4b5332729ed98a16bcd221a9318eb51
  imagePullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  env:
    PORT: "3000"
    NODE_ENV: production
    JWT_PRIVATE_KEY_PATH: /app/secrets/jwt_private_key.pem
    EMAIL_SERVICE_URL: http://email-service.email-service.svc.cluster.local:8080
  secretName: clos-secrets
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 6
    cpuTarget: 70
    memoryTarget: 80

# Frontend (nginx)
frontend:
  image: ghcr.io/emmguardia/clos-de-la-reine-front@sha256:94b3377b0c2c487764470179b8b90b82facfe99d46f1693be20b723164bfd79d
  replicas: 1
  serviceType: NodePort
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 6
    cpuTarget: 70
    memoryTarget: 80
