name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # On installe Node car Snyk en a besoin pour parser tes dépendances JS/TS
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 1. Analyse du CODE (SAST)
      # On force l'output dans un fichier et on affiche le début pour débugger en cas de "Unexpected token E"
      - name: Snyk Code test
        run: |
          snyk code test --sarif > snyk-code.sarif || true
          echo "--- DEBUG : Aperçu du fichier SARIF ---"
          head -n 20 snyk-code.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 2. Analyse des DEPENDANCES (SCA)
      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 3. Analyse KUBERNETES / HELM (IaC)
      - name: Snyk IaC test and report
        run: snyk iac test --report || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 4. Upload du rapport vers GitHub (Uniquement si c'est un vrai JSON)
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
        # On n'exécute l'upload que si le fichier commence bien par une accolade '{' (donc du JSON)
        if: success()
